name: Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
   my_test:
     runs-on: ubuntu-latest
     name: Install Bats common libs
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Setup BATS
         uses: mig4/setup-bats@v1
       - name: Setup Bats libs
         uses: brokenpip3/setup-bats-libs@0.0.2
         
   build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make install

      - name: Format
        run: make format
        
      - name: Lint
        run: make lint
        
